const assertEqual = require('../assertEqual');
assertEqual("Lighthouse Labs", "Bootcamp");
assertEqual(1, 1);
assertEqual("LHL", "LHL");
assertEqual(1, '1');
assertEqual(1, "Bootcamp");
assertEqual(1, 1);
assertEqual("Lighthouse Labs", "Bootcamp");
assertEqual(true, 1);
assertEqual(false, false);